public class TestPlanImplementation {
    public static void main(String[] args) {
        DecimalToNewBase number = new DecimalToNewBase(0);
        System.out.println(number.decToBaseTwo());
        System.out.println(number.decToBaseThree());
        System.out.println(number.decToBaseFive());
        System.out.println(number.decToBaseEight());
        System.out.println(number.decToBaseNine());
        System.out.println(number.decToBaseTwelve());
        System.out.println(number.decToBaseSixteen());
        System.out.println(number.DecToN(16));
        System.out.println();
        
        number = new DecimalToNewBase(1);
        System.out.println(number.decToBaseTwo());
        System.out.println(number.decToBaseThree());
        System.out.println(number.decToBaseFive());
        System.out.println(number.decToBaseEight());
        System.out.println(number.decToBaseNine());
        System.out.println(number.decToBaseTwelve());
        System.out.println(number.decToBaseSixteen());
        System.out.println(number.DecToN(16));
        System.out.println();
        number = new DecimalToNewBase(2);
        System.out.println(number.decToBaseTwo());
        System.out.println(number.decToBaseThree());
        System.out.println(number.decToBaseFive());
        System.out.println(number.decToBaseEight());
        System.out.println(number.decToBaseNine());
        System.out.println(number.decToBaseTwelve());
        System.out.println(number.decToBaseSixteen());
        System.out.println(number.DecToN(16));
        System.out.println();
        number = new DecimalToNewBase(3);
        System.out.println(number.decToBaseTwo());
        System.out.println(number.decToBaseThree());
        System.out.println(number.decToBaseFive());
        System.out.println(number.decToBaseEight());
        System.out.println(number.decToBaseNine());
        System.out.println(number.decToBaseTwelve());
        System.out.println(number.decToBaseSixteen());
        System.out.println(number.DecToN(16));
        System.out.println();
        number = new DecimalToNewBase(4);
        System.out.println(number.decToBaseTwo());
        System.out.println(number.decToBaseThree());
        System.out.println(number.decToBaseFive());
        System.out.println(number.decToBaseEight());
        System.out.println(number.decToBaseNine());
        System.out.println(number.decToBaseTwelve());
        System.out.println(number.decToBaseSixteen());
        System.out.println(number.DecToN(16));
        System.out.println();
        number = new DecimalToNewBase(5);
        System.out.println(number.decToBaseTwo());
        System.out.println(number.decToBaseThree());
        System.out.println(number.decToBaseFive());
        System.out.println(number.decToBaseEight());
        System.out.println(number.decToBaseNine());
        System.out.println(number.decToBaseTwelve());
        System.out.println(number.decToBaseSixteen());
        System.out.println(number.DecToN(16));
        System.out.println();
        number = new DecimalToNewBase(6);
        System.out.println(number.decToBaseTwo());
        System.out.println(number.decToBaseThree());
        System.out.println(number.decToBaseFive());
        System.out.println(number.decToBaseEight());
        System.out.println(number.decToBaseNine());
        System.out.println(number.decToBaseTwelve());
        System.out.println(number.decToBaseSixteen());
        System.out.println(number.DecToN(16));
        System.out.println();
        number = new DecimalToNewBase(7);
        System.out.println(number.decToBaseTwo());
        System.out.println(number.decToBaseThree());
        System.out.println(number.decToBaseFive());
        System.out.println(number.decToBaseEight());
        System.out.println(number.decToBaseNine());
        System.out.println(number.decToBaseTwelve());
        System.out.println(number.decToBaseSixteen());
        System.out.println(number.DecToN(16));
        System.out.println();
        number = new DecimalToNewBase(8);
        System.out.println(number.decToBaseTwo());
        System.out.println(number.decToBaseThree());
        System.out.println(number.decToBaseFive());
        System.out.println(number.decToBaseEight());
        System.out.println(number.decToBaseNine());
        System.out.println(number.decToBaseTwelve());
        System.out.println(number.decToBaseSixteen());
        System.out.println(number.DecToN(16));
        System.out.println();
        number = new DecimalToNewBase(9);
        System.out.println(number.decToBaseTwo());
        System.out.println(number.decToBaseThree());
        System.out.println(number.decToBaseFive());
        System.out.println(number.decToBaseEight());
        System.out.println(number.decToBaseNine());
        System.out.println(number.decToBaseTwelve());
        System.out.println(number.decToBaseSixteen());
        System.out.println(number.DecToN(16));
        System.out.println();
        number = new DecimalToNewBase(10);
        System.out.println(number.decToBaseTwo());
        System.out.println(number.decToBaseThree());
        System.out.println(number.decToBaseFive());
        System.out.println(number.decToBaseEight());
        System.out.println(number.decToBaseNine());
        System.out.println(number.decToBaseTwelve());
        System.out.println(number.decToBaseSixteen());
        System.out.println(number.DecToN(16));
        System.out.println();
        number = new DecimalToNewBase(11);
        System.out.println(number.decToBaseTwo());
        System.out.println(number.decToBaseThree());
        System.out.println(number.decToBaseFive());
        System.out.println(number.decToBaseEight());
        System.out.println(number.decToBaseNine());
        System.out.println(number.decToBaseTwelve());
        System.out.println(number.decToBaseSixteen());
        System.out.println(number.DecToN(16));
        System.out.println();
        number = new DecimalToNewBase(12);
        System.out.println(number.decToBaseTwo());
        System.out.println(number.decToBaseThree());
        System.out.println(number.decToBaseFive());
        System.out.println(number.decToBaseEight());
        System.out.println(number.decToBaseNine());
        System.out.println(number.decToBaseTwelve());
        System.out.println(number.decToBaseSixteen());
        System.out.println(number.DecToN(16));
        System.out.println();
        number = new DecimalToNewBase(13);
        System.out.println(number.decToBaseTwo());
        System.out.println(number.decToBaseThree());
        System.out.println(number.decToBaseFive());
        System.out.println(number.decToBaseEight());
        System.out.println(number.decToBaseNine());
        System.out.println(number.decToBaseTwelve());
        System.out.println(number.decToBaseSixteen());
        System.out.println(number.DecToN(16));
        System.out.println();
        number = new DecimalToNewBase(15);
        System.out.println(number.decToBaseTwo());
        System.out.println(number.decToBaseThree());
        System.out.println(number.decToBaseFive());
        System.out.println(number.decToBaseEight());
        System.out.println(number.decToBaseNine());
        System.out.println(number.decToBaseTwelve());
        System.out.println(number.decToBaseSixteen());
        System.out.println(number.DecToN(16));
        System.out.println();
        number = new DecimalToNewBase(16);
        System.out.println(number.decToBaseTwo());
        System.out.println(number.decToBaseThree());
        System.out.println(number.decToBaseFive());
        System.out.println(number.decToBaseEight());
        System.out.println(number.decToBaseNine());
        System.out.println(number.decToBaseTwelve());
        System.out.println(number.decToBaseSixteen());
        System.out.println(number.DecToN(16));
        System.out.println();
        number = new DecimalToNewBase(17);
        System.out.println(number.decToBaseTwo());
        System.out.println(number.decToBaseThree());
        System.out.println(number.decToBaseFive());
        System.out.println(number.decToBaseEight());
        System.out.println(number.decToBaseNine());
        System.out.println(number.decToBaseTwelve());
        System.out.println(number.decToBaseSixteen());
        System.out.println(number.DecToN(16));
        System.out.println();
        number = new DecimalToNewBase(128);
        System.out.println(number.decToBaseTwo());
        System.out.println(number.decToBaseThree());
        System.out.println(number.decToBaseFive());
        System.out.println(number.decToBaseEight());
        System.out.println(number.decToBaseNine());
        System.out.println(number.decToBaseTwelve());
        System.out.println(number.decToBaseSixteen());
        System.out.println(number.DecToN(16));
        System.out.println();
        number = new DecimalToNewBase(255);
        System.out.println(number.decToBaseTwo());
        System.out.println(number.decToBaseThree());
        System.out.println(number.decToBaseFive());
        System.out.println(number.decToBaseEight());
        System.out.println(number.decToBaseNine());
        System.out.println(number.decToBaseTwelve());
        System.out.println(number.decToBaseSixteen());
        System.out.println(number.DecToN(16));
        System.out.println();
        number = new DecimalToNewBase(256);
        System.out.println(number.decToBaseTwo());
        System.out.println(number.decToBaseThree());
        System.out.println(number.decToBaseFive());
        System.out.println(number.decToBaseEight());
        System.out.println(number.decToBaseNine());
        System.out.println(number.decToBaseTwelve());
        System.out.println(number.decToBaseSixteen());
        System.out.println(number.DecToN(16));
        System.out.println();
        number = new DecimalToNewBase(1024);
        System.out.println(number.decToBaseTwo());
        System.out.println(number.decToBaseThree());
        System.out.println(number.decToBaseFive());
        System.out.println(number.decToBaseEight());
        System.out.println(number.decToBaseNine());
        System.out.println(number.decToBaseTwelve());
        System.out.println(number.decToBaseSixteen());
        System.out.println(number.DecToN(16));
        System.out.println();
        number = new DecimalToNewBase(1025);
        System.out.println(number.decToBaseTwo());
        System.out.println(number.decToBaseThree());
        System.out.println(number.decToBaseFive());
        System.out.println(number.decToBaseEight());
        System.out.println(number.decToBaseNine());
        System.out.println(number.decToBaseTwelve());
        System.out.println(number.decToBaseSixteen());
        System.out.println(number.DecToN(16));
        System.out.println();
    }
}
